include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/maven-building-functional-unit.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/license-listing.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-functional-unit.yml'

stages:
  - build-lib
  - build-service
  - license-list
  - package
  - test-package
  - deploy

variables:
  DOCKER_BUILD_ARGS: --build-arg PARENT_IMAGE_NAME=${REDMIC_SERVER_IMAGE_NAME} --build-arg PARENT_IMAGE_TAG=${REDMIC_SERVER_IMAGE_TAG}
  LOGGING_LEVEL_ROOT: error
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: error
  LOGGING_LEVEL_ES_REDMIC: error

maven-build-view:
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - mvn -f elasticsearch-cluster-runner compile exec:java -Dexec.args="-numOfNode 1 -clusterName ${ELASTIC_CLUSTERNAME}" &
