version: '3.5'

services:
  atlas-commands:
    environment:
      SPRING_PROFILES_ACTIVE: pre
    deploy:
      placement:
        constraints:
          - node.hostname == ${ATLAS_COMMANDS_PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-hostname}
      resources:
        limits:
          cpus: '${ATLAS_COMMANDS_RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${ATLAS_COMMANDS_RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${ATLAS_COMMANDS_RESOURCES_RESERVATIONS_CPUS:-0.01}'
          memory: ${ATLAS_COMMANDS_RESOURCES_RESERVATIONS_MEMORY:-410M}

volumes:
  commands-vol:
    name: ${COMMANDS_VOL_NAME:-${UNIT_NAME}-commands-{{.Task.Slot}}-vol}
