services:
  atlas-commands:
    environment:
      SPRING_PROFILES_ACTIVE: pre
    deploy:
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.01}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-410M}

volumes:
  commands-vol:
    name: atlas-commands-{{.Task.Slot}}-vol
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},vers=${VOL_VERS},${VOL_OPTS}
      device: :${VOL_DEVICE_PREFIX}/atlas-commands-{{.Task.Slot}}-vol/

