version: '3.9'

services:
  atlas-view:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/server/atlas}:${IMAGE_TAG:-latest}
    environment:
      SERVER_PORT: ${PORT}
      OAUTH_CLIENT_ID:
      OAUTH_CLIENT_SECRET:
      ELASTIC_CLUSTERNAME:
      ELASTIC_USER:
      ELASTIC_PASSWORD:
      MICROSERVICE_NAME: ${UNIT_NAME}-view
      SPRING_KAFKA_CLIENT_ID:
      JAVA_OPTS:
    networks:
      elastic-net:
      metric-net:
      kafka-net:
      redmic-net:
      traefik-net:
    healthcheck:
      test: wget --spider -q http://localhost:${PORT}/api/${UNIT_NAME}/view/actuator/health
      interval: ${ATLAS_VIEW_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${ATLAS_VIEW_HEALTHCHECK_TIMEOUT:-15s}
      retries: ${ATLAS_VIEW_HEALTHCHECK_RETRIES:-10}
      start_period: ${ATLAS_VIEW_HEALTHCHECK_START_PERIOD:-3m}
    deploy:
      mode: replicated
      replicas: ${ATLAS_VIEW_REPLICAS:-1}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.redmic-atlas-view.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.redmic-atlas-view.rule: (Host(`${PUBLIC_HOSTNAME}`) || Host(`${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}`)) && PathPrefix(`/api/${UNIT_NAME}/view`)
        traefik.http.services.redmic-atlas-view.loadbalancer.server.port: ${PORT}
      restart_policy:
        delay: ${ATLAS_VIEW_RESTART_DELAY:-15s}
      update_config:
        delay: ${ATLAS_VIEW_UPDATE_DELAY:-2m}

networks:
  elastic-net:
    name: ${ELASTIC_NET_NAME:-elastic6-net}
    driver: ${ELASTIC_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

  redmic-net:
    name: ${REDMIC_NET_NAME:-redmic-net}
    driver: ${REDMIC_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
