version: '3.9'

services:
  atlas-view:
    environment:
      SPRING_PROFILES_ACTIVE: pre
    deploy:
      resources:
        limits:
          cpus: '${ATLAS_VIEW_RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${ATLAS_VIEW_RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${ATLAS_VIEW_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${ATLAS_VIEW_RESOURCES_RESERVATIONS_MEMORY:-410M}
