version: '3.9'

services:
  atlas-commands:
    environment:
      SPRING_PROFILES_ACTIVE: prod
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '${ATLAS_COMMANDS_RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${ATLAS_COMMANDS_RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${ATLAS_COMMANDS_RESOURCES_RESERVATIONS_CPUS:-0.01}'
          memory: ${ATLAS_COMMANDS_RESOURCES_RESERVATIONS_MEMORY:-410M}

volumes:
  commands-vol:
    name: atlas-commands-{{.Task.Slot}}-vol
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared
