version: '3.5'

services:
  atlas-commands:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.01'
          memory: 410M

volumes:
  commands-vol:
    name: "${UNIT_NAME}-commands-{{.Task.Slot}}-vol"
