version: '3.9'

services:
  atlas-commands:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/server/atlas}:${IMAGE_TAG:-latest}
    environment:
      SERVER_PORT: ${PORT}
      OAUTH_CLIENT_ID:
      OAUTH_CLIENT_SECRET:
      MICROSERVICE_NAME: ${UNIT_NAME}-commands
      SPRING_KAFKA_CLIENT_ID:
      JAVA_OPTS:
    networks:
      metric-net:
      kafka-net:
      redmic-net:
      traefik-net:
    volumes:
      - commands-vol:/tmp/kafka
    healthcheck:
      test: wget --spider -q http://localhost:${PORT}/api/${UNIT_NAME}/commands/actuator/health
      interval: ${ATLAS_COMMANDS_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${ATLAS_COMMANDS_HEALTHCHECK_TIMEOUT:-15s}
      retries: ${ATLAS_COMMANDS_HEALTHCHECK_RETRIES:-10}
      start_period: ${ATLAS_COMMANDS_HEALTHCHECK_START_PERIOD:-3m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.redmic-atlas-commands.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.redmic-atlas-commands.rule: (Host(`${PUBLIC_HOSTNAME}`) || Host(`${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}`)) && PathPrefix(`/api/${UNIT_NAME}/commands`)
        traefik.http.services.redmic-atlas-commands.loadbalancer.server.port: ${PORT}
      restart_policy:
        delay: ${ATLAS_COMMANDS_RESTART_DELAY:-15s}
      update_config:
        delay: ${ATLAS_COMMANDS_UPDATE_DELAY:-5m}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

  redmic-net:
    name: ${REDMIC_NET_NAME:-redmic-net}
    driver: ${REDMIC_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
