version: '3.5'

services:
  atlas-commands:
    environment:
      SPRING_PROFILES_ACTIVE: pre
    deploy:
      placement:
        constraints:
          - node.hostname == ${ATLAS_COMMANDS_PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-hostname}
      resources:
        limits:
          cpus: '${ATLAS_COMMANDS_RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${ATLAS_COMMANDS_RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${ATLAS_COMMANDS_RESOURCES_RESERVATIONS_CPUS:-0.01}'
          memory: ${ATLAS_COMMANDS_RESOURCES_RESERVATIONS_MEMORY:-410M}

volumes:
  commands-vol:
    name: ${COMMANDS_VOL_NAME:-atlas-commands-{{.Task.Slot}}-vol}
    driver: local
    driver_opts:
      type: ${COMMANDS_VOL_TYPE:-nfs4}
      o: addr=${COMMANDS_VOL_ADDR:-127.0.0.1},${COMMANDS_VOL_OPTIONS:-rw,nolock,noatime,tcp,rsize=8192,wsize=8192,timeo=14}
      device: ${COMMANDS_VOL_DEVICE:-:/atlas-commands-{{.Task.Slot}}-vol/}
